PKG_ARCH = 		*
COMMENT = 		visual toolkit library for 3D rendering
CATEGORIES = 		math devel
HOMEPAGE = 		http://www.vtk.org/
VERSION = 		8.2.0
DISTNAME = 		VTK-${VERSION}
PKGNAME = 		${DISTNAME}
MAINTAINER =		Charlie Burnett <burne251@umn.edu>

SHARED_LIBS +=		vtkChartsCore 				1 # 8.2
SHARED_LIBS +=		vtkCommonColor 				1 # 8.2
SHARED_LIBS +=		vtkCommonComputationalGeometry 		1 # 8.2
SHARED_LIBS +=		vtkCommonCore 				1 # 8.2
SHARED_LIBS +=		vtkCommonDataModel 			1 # 8.2
SHARED_LIBS +=		vtkCommonExecutionModel 		1 # 8.2
SHARED_LIBS +=		vtkCommonMath 				1 # 8.2
SHARED_LIBS +=		vtkCommonMisc 				1 # 8.2
SHARED_LIBS +=		vtkCommonSystem 			1 # 8.2
SHARED_LIBS +=		vtkCommonTransforms 			1 # 8.2
SHARED_LIBS +=		vtkDICOMParser 				1 # 8.2
SHARED_LIBS +=		vtkDomainsChemistry 			1 # 8.2
SHARED_LIBS +=		vtkDomainsChemistryOpenGL2 		1 # 8.2
SHARED_LIBS +=		vtkFiltersAMR 				1 # 8.2
SHARED_LIBS +=		vtkFiltersCore 				1 # 8.2
SHARED_LIBS +=		vtkFiltersExtraction 			1 # 8.2
SHARED_LIBS +=		vtkFiltersFlowPaths 			1 # 8.2
SHARED_LIBS +=		vtkFiltersGeneral 			1 # 8.2
SHARED_LIBS +=		vtkFiltersGeneric 			1 # 8.2
SHARED_LIBS +=		vtkFiltersGeometry 			1 # 8.2
SHARED_LIBS +=		vtkFiltersHybrid 			1 # 8.2
SHARED_LIBS +=		vtkFiltersHyperTree 			1 # 8.2
SHARED_LIBS +=		vtkFiltersImaging 			1 # 8.2
SHARED_LIBS +=		vtkFiltersModeling 			1 # 8.2
SHARED_LIBS +=		vtkFiltersParallel 			1 # 8.2
SHARED_LIBS +=		vtkFiltersParallelImaging 		1 # 8.2
SHARED_LIBS +=		vtkFiltersPoints 			1 # 8.2
SHARED_LIBS +=		vtkFiltersProgrammable 			1 # 8.2
SHARED_LIBS +=		vtkFiltersSMP 				1 # 8.2
SHARED_LIBS +=		vtkFiltersSelection 			1 # 8.2
SHARED_LIBS +=		vtkFiltersSources 			1 # 8.2
SHARED_LIBS +=		vtkFiltersStatistics 			1 # 8.2
SHARED_LIBS +=		vtkFiltersTexture 			1 # 8.2
SHARED_LIBS +=		vtkFiltersTopology 			1 # 8.2
SHARED_LIBS +=		vtkFiltersVerdict 			1 # 8.2
SHARED_LIBS +=		vtkGeovisCore 				1 # 8.2
SHARED_LIBS +=		vtkIOAMR 				1 # 8.2
SHARED_LIBS +=		vtkIOAsynchronous 			1 # 8.2
SHARED_LIBS +=		vtkIOCityGML 				1 # 8.2
SHARED_LIBS +=		vtkIOCore 				1 # 8.2
SHARED_LIBS +=		vtkIOEnSight 				1 # 8.2
SHARED_LIBS +=		vtkIOExodus 				1 # 8.2
SHARED_LIBS +=		vtkIOExport 				1 # 8.2
SHARED_LIBS +=		vtkIOExportOpenGL2 			1 # 8.2
SHARED_LIBS +=		vtkIOExportPDF 				1 # 8.2
SHARED_LIBS +=		vtkIOGeometry 				1 # 8.2
SHARED_LIBS +=		vtkIOImage 				1 # 8.2
SHARED_LIBS +=		vtkIOImport 				1 # 8.2
SHARED_LIBS +=		vtkIOInfovis 				1 # 8.2
SHARED_LIBS +=		vtkIOLSDyna 				1 # 8.2
SHARED_LIBS +=		vtkIOLegacy 				1 # 8.2
SHARED_LIBS +=		vtkIOMINC 				1 # 8.2
SHARED_LIBS +=		vtkIOMovie 				1 # 8.2
SHARED_LIBS +=		vtkIONetCDF 				1 # 8.2
SHARED_LIBS +=		vtkIOPLY 				1 # 8.2
SHARED_LIBS +=		vtkIOParallel 				1 # 8.2
SHARED_LIBS +=		vtkIOParallelXML 			1 # 8.2
SHARED_LIBS +=		vtkIOSQL 				1 # 8.2
SHARED_LIBS +=		vtkIOSegY 				1 # 8.2
SHARED_LIBS +=		vtkIOTecplotTable 			1 # 8.2
SHARED_LIBS +=		vtkIOVeraOut 				1 # 8.2
SHARED_LIBS +=		vtkIOVideo 				1 # 8.2
SHARED_LIBS +=		vtkIOXML 				1 # 8.2
SHARED_LIBS +=		vtkIOXMLParser 				1 # 8.2
SHARED_LIBS +=		vtkImagingColor 			1 # 8.2
SHARED_LIBS +=		vtkImagingCore 				1 # 8.2
SHARED_LIBS +=		vtkImagingFourier 			1 # 8.2
SHARED_LIBS +=		vtkImagingGeneral 			1 # 8.2
SHARED_LIBS +=		vtkImagingHybrid 			1 # 8.2
SHARED_LIBS +=		vtkImagingMath 				1 # 8.2
SHARED_LIBS +=		vtkImagingMorphological 		1 # 8.2
SHARED_LIBS +=		vtkImagingSources 			1 # 8.2
SHARED_LIBS +=		vtkImagingStatistics 			1 # 8.2
SHARED_LIBS +=		vtkImagingStencil 			1 # 8.2
SHARED_LIBS +=		vtkInfovisCore 				1 # 8.2
SHARED_LIBS +=		vtkInfovisLayout 			1 # 8.2
SHARED_LIBS +=		vtkInteractionImage 			1 # 8.2
SHARED_LIBS +=		vtkInteractionStyle 			1 # 8.2
SHARED_LIBS +=		vtkInteractionWidgets 			1 # 8.2
SHARED_LIBS +=		vtkNetCDF 				1 # 8.2
SHARED_LIBS +=		vtkParallelCore 			1 # 8.2
SHARED_LIBS +=		vtkRenderingAnnotation 			1 # 8.2
SHARED_LIBS +=		vtkRenderingContext2D 			1 # 8.2
SHARED_LIBS +=		vtkRenderingContextOpenGL2 		1 # 8.2
SHARED_LIBS +=		vtkRenderingCore 			1 # 8.2
SHARED_LIBS +=		vtkRenderingFreeType 			1 # 8.2
SHARED_LIBS +=		vtkRenderingGL2PSOpenGL2 		1 # 8.2
SHARED_LIBS +=		vtkRenderingImage 			1 # 8.2
SHARED_LIBS +=		vtkRenderingLOD 			1 # 8.2
SHARED_LIBS +=		vtkRenderingLabel 			1 # 8.2
SHARED_LIBS +=		vtkRenderingOpenGL2 			1 # 8.2
SHARED_LIBS +=		vtkRenderingVolume 			1 # 8.2
SHARED_LIBS +=		vtkRenderingVolumeOpenGL2 		1 # 8.2
SHARED_LIBS +=		vtkViewsContext2D 			1 # 8.2
SHARED_LIBS +=		vtkViewsCore 				1 # 8.2
SHARED_LIBS +=		vtkViewsInfovis 			1 # 8.2
SHARED_LIBS +=		vtkdoubleconversion 			1 # 8.2
SHARED_LIBS +=		vtkexodusII 				1 # 8.2
SHARED_LIBS +=		vtkexpat 				1 # 8.2
SHARED_LIBS +=		vtkfreetype 				1 # 8.2
SHARED_LIBS +=		vtkgl2ps 				1 # 8.2
SHARED_LIBS +=		vtkglew 				1 # 8.2
SHARED_LIBS +=		vtkhdf5 				1 # 8.2
SHARED_LIBS +=		vtkhdf5_hl 				1 # 8.2
SHARED_LIBS +=		vtkjpeg 				1 # 8.2
SHARED_LIBS +=		vtkjsoncpp 				1 # 8.2
SHARED_LIBS +=		vtklibharu 				1 # 8.2
SHARED_LIBS +=		vtklibxml2 				1 # 8.2
SHARED_LIBS +=		vtklz4 					1 # 8.2
SHARED_LIBS +=		vtklzma 				1 # 8.2
SHARED_LIBS +=		vtkmetaio 				1 # 8.2
SHARED_LIBS +=		vtkogg 					1 # 8.2
SHARED_LIBS +=		vtkpng 					1 # 8.2
SHARED_LIBS +=		vtkproj 				1 # 8.2
SHARED_LIBS +=		vtkpugixml 				1 # 8.2
SHARED_LIBS +=		vtksqlite 				1 # 8.2
SHARED_LIBS +=		vtksys 					1 # 8.2
SHARED_LIBS +=		vtktheora 				1 # 8.2
SHARED_LIBS +=		vtktiff 				1 # 8.2
SHARED_LIBS +=		vtkverdict 				1 # 8.2
SHARED_LIBS +=		vtkzlib 				1 # 8.2

# BSD 3-clause

PERMIT_PACKAGE = 	Yes

MASTER_SITES = 		http://www.vtk.org/files/release/8.2/

COMPILER =		base-clang ports-gcc

MODULES +=		devel/cmake

USE_NINJA = 		yes

WANTLIB +=		${COMPILER_LIBCXX}

WANTLIB += 		GL GLU ICE SM X11 Xext Xt m pthread freetype

LIB_DEPENDS = 		graphics/tiff\
	  		graphics/png 

SEPARATE_BUILD =	Yes




.include <bsd.port.mk>
